window.CVSI_PLAUSIBILITY_PRETEST = {
  schema_version: "6.0",
  survey_id: "cvsi_p0_operation_grounded_8scene_plausibility_pretest_v1",
  build_id: "p0_builtin_operation_grounded_12task_r1_v1",
  instrument_version: "plausibility_v1",
  sample_contract: {
    screens_per_participant: 8,
    scenes_per_family: 2,
    distinct_tasks_within_family: true,
    intended_role_counts: { N: 2, C: 3, I: 3 },
    intended_roles_hidden_from_participant: true,
  },
  scenes: [
    ["A01", "A", "N", "general_interior"], ["A01", "A", "C", "art_studio"], ["A01", "A", "I", "accounting_office"],
    ["A02", "A", "N", "plain_studio"], ["A02", "A", "C", "figure_drawing_classroom"], ["A02", "A", "I", "electronics_repair_desk"],
    ["A03", "A", "N", "general_interior"], ["A03", "A", "C", "gallery_prep"], ["A03", "A", "I", "accounting_office"],
    ["B01", "B", "N", "ordinary_desk"], ["B01", "B", "C", "design_workstation"], ["B01", "B", "I", "kitchen_counter"],
    ["B02", "B", "N", "ordinary_desk"], ["B02", "B", "C", "print_shop"], ["B02", "B", "I", "hobby_craft_desk"],
    ["B03", "B", "N", "ordinary_desk"], ["B03", "B", "C", "office_admin_desk"], ["B03", "B", "I", "kitchen_counter"],
    ["C01", "C", "N", "plain_tabletop"], ["C01", "C", "C", "forensic_desk"], ["C01", "C", "I", "cafe_table"],
    ["C02", "C", "N", "plain_room"], ["C02", "C", "C", "newsroom_editing_bay"], ["C02", "C", "I", "casual_living_room"],
    ["C03", "C", "N", "plain_tabletop"], ["C03", "C", "C", "archive_desk"], ["C03", "C", "I", "cafe_table"],
    ["D01", "D", "N", "plain_digital_editing_desk"], ["D01", "D", "C", "design_studio"], ["D01", "D", "I", "classroom_lunch_table"],
    ["D02", "D", "N", "plain_digital_editing_desk"], ["D02", "D", "C", "publishing_workstation"], ["D02", "D", "I", "home_storage_shelf"],
    ["D03", "D", "N", "plain_digital_editing_desk"], ["D03", "D", "C", "creator_desk"], ["D03", "D", "I", "classroom_lunch_table"],
  ].map(([task_id, family, intended_role, context_template]) => ({
    scene_id: `${task_id}_${intended_role}1`,
    task_id,
    family,
    intended_role,
    realization: 1,
    context_template,
    src: `assets/${task_id}/${intended_role}.png`,
  })),
};
