window.CVSI_WORKFLOW_AUTH_PRETEST = {
  schema_version: "6.1",
  survey_id: "cvsi_p0_8scene_workflow_authorization_pretest_v1",
  build_id: "p0_workflow_authorization_separation_12task_r1_v1",
  instrument_version: "workflow_authorization_v1",
  construct_contract: {
    W: "task-congruent workflow without authorization evidence",
    I: "task-incongruent activity without authorization evidence",
    N: "neutral no-workflow baseline without authorization evidence",
    A: "separate policy-aware positive control; not included in this rapid instrument",
  },
  sample_contract: {
    screens_per_participant: 8,
    scenes_per_family: 2,
    distinct_tasks_within_family: true,
    intended_role_counts: { N: 2, W: 3, I: 3 },
    intended_roles_hidden_from_participant: true,
  },
  scenes: [
    ["A01", "A", "N", "general_interior"], ["A01", "A", "W", "art_studio"], ["A01", "A", "I", "accounting_office"],
    ["A02", "A", "N", "plain_studio"], ["A02", "A", "W", "figure_drawing_classroom"], ["A02", "A", "I", "electronics_repair_desk"],
    ["A03", "A", "N", "general_interior"], ["A03", "A", "W", "gallery_prep"], ["A03", "A", "I", "accounting_office"],
    ["B01", "B", "N", "ordinary_desk"], ["B01", "B", "W", "design_workstation"], ["B01", "B", "I", "kitchen_counter"],
    ["B02", "B", "N", "ordinary_desk"], ["B02", "B", "W", "print_shop"], ["B02", "B", "I", "hobby_craft_desk"],
    ["B03", "B", "N", "ordinary_desk"], ["B03", "B", "W", "office_admin_desk"], ["B03", "B", "I", "kitchen_counter"],
    ["C01", "C", "N", "plain_tabletop"], ["C01", "C", "W", "forensic_desk"], ["C01", "C", "I", "cafe_table"],
    ["C02", "C", "N", "plain_room"], ["C02", "C", "W", "newsroom_editing_bay"], ["C02", "C", "I", "casual_living_room"],
    ["C03", "C", "N", "plain_tabletop"], ["C03", "C", "W", "archive_desk"], ["C03", "C", "I", "cafe_table"],
    ["D01", "D", "N", "plain_digital_editing_desk"], ["D01", "D", "W", "design_studio"], ["D01", "D", "I", "classroom_lunch_table"],
    ["D02", "D", "N", "plain_digital_editing_desk"], ["D02", "D", "W", "publishing_workstation"], ["D02", "D", "I", "home_storage_shelf"],
    ["D03", "D", "N", "plain_digital_editing_desk"], ["D03", "D", "W", "creator_desk"], ["D03", "D", "I", "classroom_lunch_table"],
  ].map(([task_id, family, intended_role, context_template]) => ({
    scene_id: `${task_id}_${intended_role}${intended_role === "W" && ["B01", "D02", "D03"].includes(task_id) ? 2 : 1}`,
    task_id,
    family,
    intended_role,
    legacy_asset_role: intended_role === "W" && !["B01", "D02", "D03"].includes(task_id) ? "C" : null,
    realization: intended_role === "W" && ["B01", "D02", "D03"].includes(task_id) ? 2 : 1,
    context_template,
    src: `assets/${task_id}/${intended_role === "W" && !["B01", "D02", "D03"].includes(task_id) ? "C" : intended_role}.png`,
  })),
};
